name: ML Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Train model
      run: |
        python src/train_model.py
        ls -la  # Verify file creation
    
    - name: Upload model (Alternative Method)
      if: always()
      run: |
        # Create a temporary directory
        mkdir -p artifact-upload
        
        # Copy the model file
        cp iris_model.joblib artifact-upload/
        
        # Create a checksum for verification
        sha256sum artifact-upload/iris_model.joblib > artifact-upload/checksum.txt
        
        # Upload as a zip archive
        zip -r model-artifact.zip artifact-upload/
        
        # Use GitHub's artifact upload API
        curl -X POST \
          -H "Authorization: bearer ${{ github.token }}" \
          -H "Content-Type: application/zip" \
          --data-binary @model-artifact.zip \
          "https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts?name=iris-model"
        
        echo "Artifact upload complete"
