name: ML Pipeline Debug

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Test artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: README.md  # Using a file we know exists
